### ISSUE TITLE
Bring Node & React.js up to date

### ISSUE THREAD

**Issue by kweerious** [DerbyBoutTime/bouttime#131]
The project is currently very far behind the current Node & React versions. Now that the node.js/io.js split is resolved we need to get back up to speed with the latest and handle any deprecations.

Notes for React changes 0.14.x, 15.x and it has a new version scheme:
- it's two packages now
- addons have been broken up
- classSet needs to be updated everywhere to use https://github.com/JedWatson/classnames
- probably need to address the <span> changes
- More notes: http://reactkungfu.com/2015/10/upgrading-to-react-014/

`npm install` warnings:
<details>

```
npm WARN deprecated react-tools@0.13.3: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated pangyp@2.3.3: use node-gyp@3+ instead
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global cover@0.2.9 should be installed with -g
npm WARN prefer global jshint@2.9.3 should be installed with -g
npm WARN prefer global pangyp@2.3.3 should be installed with -g
```

</details>

**Comment by kweerious** [comment]
Assigning this so I remember to start looking at it.

**Comment by adtaylor** [comment]
Hi @kweerious, I've only recently found out about bouttime and I am really excited about seeing this used live!

Is this project looking for engineers or is it just being developed in the open?

In my day job (lead JS engineer) I build and maintain React/Relay apps, would be happy to take a look at this issue if it helps?

**Comment by kweerious** [comment]
We welcome and encourage all development! There's a branch here with some node4 changes as well. Any effort or discussion you are willing to provide we work to channel.

**Comment by kweerious** [comment]
@adtaylor here's a link https://github.com/WFTDA/bouttime/tree/miketheman/upgrade-node-4 with some work from @miketheman. I believe everything runs but the tests aren't passing.

**Comment by adtaylor** [comment]
@kweerious cheers. I'll take a look at getting those test passing.
